# Generated by Django 4.2.7 on 2026-02-14 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript')], max_length=20, verbose_name='Мова')),
                ('short_description', models.CharField(max_length=300, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
                ('duration_hours', models.PositiveIntegerField(default=24, verbose_name='Тривалість (год)')),
                ('level', models.CharField(default='Початковий', max_length=50, verbose_name='Рівень')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('icon', models.CharField(default='🐍', max_length=10, verbose_name='Іконка/емодзі')),
                ('color', models.CharField(default='#3776ab', max_length=7, verbose_name='Колір (hex)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField()),
                ('content', models.TextField(verbose_name='Контент (HTML/Markdown)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('duration_minutes', models.PositiveIntegerField(default=15, verbose_name='Хвилин')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогрес',
                'verbose_name_plural': 'Прогрес',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('instruction', models.TextField(verbose_name='Інструкція')),
                ('starter_code', models.TextField(blank=True, verbose_name='Початковий код')),
                ('solution', models.TextField(blank=True, verbose_name='Рішення (для перевірки)')),
                ('hint', models.TextField(blank=True, verbose_name='Підказка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
                'ordering': ['lesson', 'order'],
            },
        ),
    ]
