# Generated by Django 5.2.11 on 2026-02-14 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('icon', models.CharField(default='🏆', max_length=20, verbose_name='Іконка')),
                ('points_reward', models.PositiveIntegerField(default=0, verbose_name='Бонус балів')),
                ('condition_type', models.CharField(choices=[('first_lesson', 'Перший завершений урок'), ('lessons_5', '5 уроків'), ('lessons_10', '10 уроків'), ('quiz_perfect', 'Ідеальний тест'), ('streak_3', 'Вогник 3 дні'), ('streak_7', 'Вогник 7 днів'), ('points_100', '100 балів'), ('points_500', '500 балів'), ('first_quiz', 'Перший пройдений тест')], default='first_lesson', max_length=50, verbose_name='Умова')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Досягнення',
                'verbose_name_plural': 'Досягнення',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('start_at', models.DateTimeField(verbose_name='Початок')),
                ('end_at', models.DateTimeField(verbose_name='Кінець')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Змагання',
                'verbose_name_plural': 'Змагання',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True)),
                ('min_points', models.PositiveIntegerField(default=0, verbose_name='Мін. балів')),
                ('icon', models.CharField(default='🥉', max_length=20, verbose_name='Іконка')),
                ('color', models.CharField(default='#cd7f32', max_length=7, verbose_name='Колір')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ліга',
                'verbose_name_plural': 'Ліги',
                'ordering': ['order', 'min_points'],
            },
        ),
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Сесія')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Бали')),
                ('streak_days', models.PositiveIntegerField(default=0, verbose_name='Вогник (дні поспіль)')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Остання активність')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='courses.league')),
            ],
            options={
                'verbose_name': 'Ігровий профіль',
                'verbose_name_plural': 'Ігрові профілі',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('quiz_type', models.CharField(choices=[('single_choice', 'Один правильний варіант'), ('multiple_choice', 'Кілька правильних'), ('true_false', 'Так / Ні'), ('flashcard', 'Картки (питання–відповідь)'), ('match_pairs', "З'єднати пари"), ('ordering', 'Впорядкування'), ('fill_blank', 'Пропущене слово / код')], max_length=20, verbose_name='Тип')),
                ('is_practice', models.BooleanField(default=False, verbose_name='Тренувальний режим (без оцінки)')),
                ('points_per_question', models.PositiveIntegerField(default=10, verbose_name='Балів за питання')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст питання / передня сторона картки')),
                ('question_type', models.CharField(blank=True, choices=[('single_choice', 'Один правильний варіант'), ('multiple_choice', 'Кілька правильних'), ('true_false', 'Так / Ні'), ('flashcard', 'Картки (питання–відповідь)'), ('match_pairs', "З'єднати пари"), ('ordering', 'Впорядкування'), ('fill_blank', 'Пропущене слово / код')], max_length=20, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дані (варіанти, пари, тощо)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Бали')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='Макс. балів')),
                ('is_practice', models.BooleanField(default=False, verbose_name='Тренувальний режим')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Спроба тесту',
                'verbose_name_plural': 'Спроби тестів',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Сесія')),
                ('score', models.PositiveSmallIntegerField(default=5, verbose_name='Оцінка (1–5)')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='courses.achievement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отримане досягнення',
                'verbose_name_plural': 'Отримані досягнення',
            },
        ),
    ]
