# Generated by Django 5.2.11 on 2026-02-24 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_achievement_competition_league_gameprofile_quiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(verbose_name='Текст задачі')),
                ('code_submitted', models.TextField(blank=True, verbose_name='Код студента')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оцінка (1–10)')),
                ('feedback', models.TextField(blank=True, verbose_name='Відгук AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_practice_attempts', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Спроба AI-практики',
                'verbose_name_plural': 'Спроби AI-практики',
                'ordering': ['-created_at'],
            },
        ),
    ]
