# Generated by Django 5.2.11 on 2026-02-24 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_ai_practice_attempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStudyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='Хвилин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_study_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Час навчання за день',
                'verbose_name_plural': 'Час навчання за день',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
