# Generated by Django 5.2.11 on 2026-02-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_daily_study_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('first_lesson', 'Перший завершений урок'), ('lessons_5', '5 уроків'), ('lessons_10', '10 уроків'), ('quiz_perfect', 'Ідеальний тест'), ('first_quiz', 'Перший пройдений тест'), ('quizzes_10', '10 пройдених тестів'), ('quizzes_50', '50 пройдених тестів'), ('quizzes_100', '100 пройдених тестів'), ('streak_3', 'Вогник 3 дні'), ('streak_7', 'Вогник 7 днів'), ('points_100', '100 балів'), ('points_500', '500 балів')], default='first_lesson', max_length=50, verbose_name='Умова'),
        ),
    ]
