# Generated by Django 5.2.11 on 2026-03-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_achievement_condition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_placement',
            field=models.BooleanField(default=False, verbose_name='Вступний тест (визначення рівня)'),
        ),
    ]
