# Generated by Django 5.2.11 on 2026-03-05 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_podcast_conversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('first_lesson', 'Перший завершений урок'), ('lessons_5', '5 уроків'), ('lessons_10', '10 уроків'), ('quiz_perfect', 'Ідеальний тест'), ('first_quiz', 'Перший пройдений тест'), ('quizzes_5', '5 пройдених тестів'), ('quizzes_10', '10 пройдених тестів'), ('quizzes_50', '50 пройдених тестів'), ('quizzes_100', '100 пройдених тестів'), ('streak_3', 'Вогник 3 дні'), ('streak_7', 'Вогник 7 днів'), ('points_100', '100 балів'), ('points_500', '500 балів')], default='first_lesson', max_length=50, verbose_name='Умова'),
        ),
        migrations.CreateModel(
            name='AILessonQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=30, verbose_name='Тип тесту')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_lesson_quiz_attempts', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_lesson_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пройдений AI-тест уроку',
                'verbose_name_plural': 'Пройдені AI-тести уроків',
                'ordering': ['-completed_at'],
            },
        ),
    ]
