# Generated by Django 5.2.11 on 2026-03-06 00:03

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_add_ai_lesson_quiz_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.avatar_upload_to, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('first_lesson', 'Перший завершений урок'), ('lessons_5', '5 уроків'), ('lessons_10', '10 уроків'), ('lessons_15', '15 уроків'), ('quiz_perfect', 'Ідеальний тест'), ('first_quiz', 'Перший пройдений тест'), ('quizzes_5', '5 пройдених тестів'), ('quizzes_10', '10 пройдених тестів'), ('quizzes_50', '50 пройдених тестів'), ('quizzes_100', '100 пройдених тестів'), ('streak_3', 'Вогник 3 дні'), ('streak_7', 'Вогник 7 днів'), ('streak_14', 'Вогник 14 днів'), ('points_100', '100 балів'), ('points_500', '500 балів'), ('points_1000', '1000 балів')], default='first_lesson', max_length=50, verbose_name='Умова'),
        ),
    ]
